[package]
name = "solve"
version = "0.1.0"
authors = ["Matthias Monschein <monschein.matthias@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
hex = "0.4.3"